#!/bin/bash

real_script=$(readlink -f "$0" 2>/dev/null || echo "$0")
SCRIPT_DIR=$(dirname "$real_script")

cd "$SCRIPT_DIR"
export PYTHONPATH="$SCRIPT_DIR:$PYTHONPATH"

[ -f ".venv/bin/activate" ] && source .venv/bin/activate

python3 main.py "$@"
